spring.application.name=food-delivery-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/food_delivery_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600
jwt.issuer=food-delivery-backend
